# Generated by Django 3.0.5 on 2021-05-08 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='tag',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
